### ISSUE TITLE
TODO: tests need secrets for GH App auth

### ISSUE THREAD

**Issue by thockin** [kubernetes/git-sync#879]
- [x] Make a way to declare env-only non-flags that still show help, logs, etc.
- [x] Deprecate --password in favor of a non-flag
- [x] - [ ] e2e support for env-flags
- [x] Make a way to make some e2e tests optional and use that in actions (or do actions wioth secrets).
- [ ] Make CI test GH app auth (need secrets)
- [ ] Make actions verify vendor
- [ ] Make actions verify flags vs manual

**Comment by thockin** [comment]
xref #886
